# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: json dicts can be added to the conn_extra field as yaml key value pairs. See the example below.

# For more information, refer to our docs: https://www.astronomer.io/docs/astro/cli/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues

airflow:
  connections:
    - conn_id: tigris_default
      conn_type: s3
      conn_host: https://fly.storage.tigris.dev
      conn_login: ${TIGRIS_ACCESS_KEY}
      conn_password: ${TIGRIS_SECRET_KEY}
      conn_extra:
        aws_access_key_id: ${TIGRIS_ACCESS_KEY}
        aws_secret_access_key: ${TIGRIS_SECRET_KEY}
    - conn_id: mongo_default
      conn_type: mongodb
      conn_host: db-dados.i50nyqj.mongodb.net
      conn_login: frank-cardoso
      conn_password: ${MONGO_PASSWORD}
      conn_schema: gearlog_erp
      conn_port: 27017
  pools:
    - pool_name: default_pool
      pool_slot: 128
      pool_description: Pool padrão para execução de tarefas
  variables:
    - variable_name: tigris_bucket
      variable_value: projeto-lakehouse-satc
    - variable_name: tigris_endpoint
      variable_value: https://fly.storage.tigris.dev
